### ISSUE TITLE
Localize no stopping sign for Puerto Rico

### ISSUE THREAD

**Issue by 1ec5** [streetcomplete/countrymetadata#1]
The country metadata for Puerto Rico correctly specifies a Puerto Rico–specific no parking sign that says “[No Estacione](https://github.com/streetcomplete/StreetComplete/blob/6609fd3c31099d02535cb618f13e572eafecc7b8/res/graphics/street%20parking/no%20parking%20sign/mutcd_text_spanish.svg)”, but it falls back to the English-language no stopping sign used on the mainland:

https://github.com/streetcomplete/StreetComplete/blob/6609fd3c31099d02535cb618f13e572eafecc7b8/app/src/main/assets/country_metadata/PR.yml#L4-L5 

According to the _Manual de Rotulación para las Vías Públicas de Puerto Rico_, Puerto Rico’s MUTCD supplement, the correct sign in Puerto Rico says “No Pare”, and then “No Estacione” below for good measure:

[<img src="https://upload.wikimedia.org/wikipedia/commons/3/3d/MUTCD-PR_R7-4.svg" width="250" alt="R7-4">](https://commons.wikimedia.org/wiki/File:MUTCD-PR_R7-4.svg)

I think it’s safe to assume that no standing signs don’t exist in Puerto Rico. The supplement doesn’t define a no standing sign. Even though it’s just a supplement, rather than a full state edition that overrides the national MUTCD, the highway authority is very consistent about only posting Spanish-language signs, so a “No Standing” sign would be very unlikely.

**Comment by westnordost** [comment]
https://www.google.de/maps/@18.4007917,-66.0561823,3a,15.4y,30.12h,80.43t/data=!3m9!1e1!3m7!1sLXFXKKxgWmlOqnv3KKWfXg!2e0!7i13312!8i6656!9m2!1b1!2i41
