### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/countrymetadata#10]
Basically the same request as https://github.com/streetcomplete/StreetComplete/issues/2157:

@westnordost Would it be fine for you to opt into Hacktoberfest by adding the `hacktoberfest` topic to the repo? Contributions are much easier in here than in the StreetComplete repository, and might lure new contributors into contributing to StreetComplete in general.

**Comment by matkoniecz** [comment]
Do we have anything that is known to be missing? Or worth verifying?

**Comment by FloEdelmann** [comment]
Adding verifiable source comments for existing data does never hurt, and data for some countries are likely missing somewhere. But I don't have anything specific in mind.

**Comment by FloEdelmann** [comment]
@westnordost As Hacktoberfest has now started, would you consider this issue please?

**Comment by westnordost** [comment]
What do i need to do?

**Comment by FloEdelmann** [comment]
1. For future PRs: Add the `hacktoberfest` topic to the repo. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics
2. For #11 (if @bgo-eiu wants to participate in the Hacktoberfest): Add the `hacktoberfest-accepted` label to the PR.

**Comment by westnordost** [comment]
hacktoberfest or hacktoberfest2022?

**Comment by riQQ** [comment]
`hacktoberfest` (see also https://hacktoberfest.com/participation/#maintainers)

**Comment by FloEdelmann** [comment]
Thank you! :)
