### ISSUE TITLE
LengthUnits in Canada

### ISSUE THREAD

**Issue by yow-guy** [streetcomplete/countrymetadata#21]
In Canada, StreetComplete uses the global default length units of metres for measurements of height and width. While all official street signs are demarcated in **metres**, signs on private property frequently use **both metres and feet/inches** or **only feet/inches**.

This has caused particular problems in completing "What height limit is indicated here?" quests on garage entrances where signs are in feet/inches and StreetComplete only allows input in metres.

Suggested fix: add the following line to countrymetadata/data/lengthUnits.yml:

``CA: [meter, foot and inch] # official signs use metric but imperial measurements common on private property``

_Apologies, new to GitHub, there is probably a way to make this fix directly_

**Comment by westnordost** [comment]
Could you show some examples? (street view)

**Comment by westnordost** [comment]
Thanks, I shall include two of these as a comment as documentation.
